### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/planningalerts-app#193]
The results page says " Pending (May include **withdraw** applications)"

**Comment by zarino** [comment]
:+1: Just came here to say the same thing!

Also, that message could probably do with some better spacing, to stop it colliding with the bar above.

![screen shot 2015-08-17 at 11 47 39](https://cloud.githubusercontent.com/assets/739624/9303409/bff2dd8c-44d5-11e5-9e64-c3526ee68021.png)

**Comment by stevenday** [comment]
I've fixed the typo now, @zarino how could we do that? I intentionally kept it closer to the Pending bar/label because it's about that status specifically, putting it in a new paragraph (for example) made it seem a separate thing..

**Comment by zarino** [comment]
@stevenday: Something like this maybe…

![screen shot 2015-08-17 at 11 54 50](https://cloud.githubusercontent.com/assets/739624/9303555/c820b6e0-44d6-11e5-8729-401eef551979.png)

The smaller type (90%) makes it clear it's not a new item in the list, and making it slightly grey reduces its visual weight.

It's not ideal, but it'll do until #189 is fixed.

**Comment by stevenday** [comment]
Thanks @zarino! I've added that styling as a new .notes class for the
sidebar, it's looking much better

## _Steve Day_

_Engineering Manager_, mySociety Services
http://www.mysociety.co.uk
