### ISSUE TITLE
Add some example searches to the homepage

### ISSUE THREAD

**Issue by stevenday** [mysociety/planningalerts-app#197]
If we're going to be promoting the app to people outside of hampshire, we should have some links to good example searches on the homepage that show off the capabilities a bit.

e.g.
- [All applications in Fordingbridge](http://openplanning.hampshirehub.net/applications/search?results=true&display=map&status=all&search=anything&location=Provost+Street%2C+Fordingbridge)
- [Extensions in Aldershot](http://openplanning.hampshirehub.net/applications/search?results=true&display=map&status=all&search=extensions&location=High+Street%2C+Aldershot)
- [County council matters in Winchester](http://openplanning.hampshirehub.net/applications/search?results=true&display=map&status=all&search=county+council+matters&location=Upper+High+Street%2C+Winchester)
- [Refused applications for extensions near SP6 1AP](http://openplanning.hampshirehub.net/applications/search?results=true&display=map&status=refused&search=extensions&location=SP6+1AP)

**Comment by davea** [comment]
I've made a start on this:

![screen shot 2015-08-25 at 16 47 52](https://cloud.githubusercontent.com/assets/4776/9471623/265bd9ba-4b49-11e5-9a2a-f6d06741898c.png)

Do we think it needs some design attention or are the simple centred links OK?

**Comment by stevenday** [comment]
I think this looks good! Maybe try squeezing them onto one or two lines with just some commas between? Otherwise the size of that bit is detracting from the main form somewhat

**Comment by davea** [comment]
Good idea, that looks much better:
![screen shot 2015-08-26 at 12 09 51](https://cloud.githubusercontent.com/assets/4776/9491985/7a74427e-4beb-11e5-89af-e5d4764b036e.png)
